#!/bin/bash
set -e

# Debugging: Print the environment variables
echo "MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}"
echo "DATABASE_CONTAINER_USERNAME: ${DATABASE_CONTAINER_USERNAME}"
echo "DATABASE_CONTAINER_PASSWORD: ${DATABASE_CONTAINER_PASSWORD}"
echo "MYSQL_DATABASE: ${MYSQL_DATABASE}"

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
    CREATE USER IF NOT EXISTS '${DATABASE_CONTAINER_USERNAME}'@'%' IDENTIFIED BY '${DATABASE_CONTAINER_PASSWORD}';
    GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${DATABASE_CONTAINER_USERNAME}'@'%';
    FLUSH PRIVILEGES;
EOSQL
